### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: loader
    type: <xref href="Microsoft.CodeAnalysis.TextLoader?alt=Microsoft.CodeAnalysis.TextLoader&text=TextLoader" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.TextLoader)
  commentId: M:Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.TextLoader)
  name: OnAnalyzerConfigDocumentTextLoaderChanged(DocumentId, TextLoader)
  fullName: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged(DocumentId, TextLoader)
  nameWithType: Workspace.OnAnalyzerConfigDocumentTextLoaderChanged(DocumentId, TextLoader)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected internal void OnAnalyzerConfigDocumentTextLoaderChanged (Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.TextLoader loader);
  - lang: fsharp
    values:
    - value: 'member this.OnAnalyzerConfigDocumentTextLoaderChanged : Microsoft.CodeAnalysis.DocumentId * Microsoft.CodeAnalysis.TextLoader -> unit'
  - lang: vb
    values:
    - value: Protected Friend Sub OnAnalyzerConfigDocumentTextLoaderChanged (documentId As DocumentId, loader As TextLoader)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Call this method when the text of a analyzer config document is changed on disk.
  metadata: {}
uid: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged*
commentId: Overload:Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged
namespace: Microsoft.CodeAnalysis
name: OnAnalyzerConfigDocumentTextLoaderChanged
fullName: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged
nameWithType: Workspace.OnAnalyzerConfigDocumentTextLoaderChanged
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentTextLoaderChanged
  - Microsoft::CodeAnalysis::Workspace::OnAnalyzerConfigDocumentTextLoaderChanged
  - OnAnalyzerConfigDocumentTextLoaderChanged
  - Workspace.OnAnalyzerConfigDocumentTextLoaderChanged
  - Workspace::OnAnalyzerConfigDocumentTextLoaderChanged
  helpviewer_keywords:
  - Workspace.OnAnalyzerConfigDocumentTextLoaderChanged method [.NET]
  - OnAnalyzerConfigDocumentTextLoaderChanged method [.NET], class Workspace
  - Workspace.OnAnalyzerConfigDocumentTextLoaderChanged(DocumentId, TextLoader) method [.NET]
  - OnAnalyzerConfigDocumentTextLoaderChanged(DocumentId, TextLoader) method [.NET], class Workspace
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
