### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Immutable.ImmutableDictionary`2?alt=System.Collections.Immutable.ImmutableDictionary&text=ImmutableDictionary" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>,<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
  name: Properties
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
  nameWithType: AnalyzerConfig.Section.Properties
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Immutable.ImmutableDictionary<string,string> Properties { get; }
  - lang: fsharp
    values:
    - value: 'member this.Properties : System.Collections.Immutable.ImmutableDictionary<string, string>'
  - lang: vb
    values:
    - value: Public ReadOnly Property Properties As ImmutableDictionary(Of String, String)
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: >-
    Keys and values for this section. All keys are lower-cased according to the

    EditorConfig specification and keys are compared case-insensitively. Values are

    lower-cased if the value appears in <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfig.ReservedValues"></xref>

    or if the corresponding key is in <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys"></xref>. Otherwise,

    the values are the literal values present in the source.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
namespace: Microsoft.CodeAnalysis
name: Properties
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
nameWithType: AnalyzerConfig.Section.Properties
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.get_Properties
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
  - Microsoft::CodeAnalysis::AnalyzerConfig::Section::Properties
  - Properties
  - Section.Properties
  - Section::Properties
  helpviewer_keywords:
  - AnalyzerConfig.Section.Properties property [.NET]
  - Properties property [.NET], class AnalyzerConfig.Section
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
