### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: documentInfo
    type: <xref href="Microsoft.CodeAnalysis.DocumentInfo?alt=Microsoft.CodeAnalysis.DocumentInfo&text=DocumentInfo" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded(Microsoft.CodeAnalysis.DocumentInfo)
  commentId: M:Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded(Microsoft.CodeAnalysis.DocumentInfo)
  name: OnAnalyzerConfigDocumentAdded(DocumentInfo)
  fullName: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded(DocumentInfo)
  nameWithType: Workspace.OnAnalyzerConfigDocumentAdded(DocumentInfo)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected internal void OnAnalyzerConfigDocumentAdded (Microsoft.CodeAnalysis.DocumentInfo documentInfo);
  - lang: fsharp
    values:
    - value: 'member this.OnAnalyzerConfigDocumentAdded : Microsoft.CodeAnalysis.DocumentInfo -> unit'
  - lang: vb
    values:
    - value: Protected Friend Sub OnAnalyzerConfigDocumentAdded (documentInfo As DocumentInfo)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Call this method when an analyzer config document is added to a project in the host environment.
  metadata: {}
uid: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded*
commentId: Overload:Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded
namespace: Microsoft.CodeAnalysis
name: OnAnalyzerConfigDocumentAdded
fullName: Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded
nameWithType: Workspace.OnAnalyzerConfigDocumentAdded
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Workspace.OnAnalyzerConfigDocumentAdded
  - Microsoft::CodeAnalysis::Workspace::OnAnalyzerConfigDocumentAdded
  - OnAnalyzerConfigDocumentAdded
  - Workspace.OnAnalyzerConfigDocumentAdded
  - Workspace::OnAnalyzerConfigDocumentAdded
  helpviewer_keywords:
  - Workspace.OnAnalyzerConfigDocumentAdded method [.NET]
  - OnAnalyzerConfigDocumentAdded method [.NET], class Workspace
  - Workspace.OnAnalyzerConfigDocumentAdded(DocumentInfo) method [.NET]
  - OnAnalyzerConfigDocumentAdded(DocumentInfo) method [.NET], class Workspace
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
