### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions?alt=Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions&text=AnalyzerConfigOptions" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: textFile
    type: <xref href="Microsoft.CodeAnalysis.AdditionalText?alt=Microsoft.CodeAnalysis.AdditionalText&text=AdditionalText" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions(Microsoft.CodeAnalysis.AdditionalText)
  commentId: M:Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions(Microsoft.CodeAnalysis.AdditionalText)
  name: GetOptions(AdditionalText)
  fullName: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions(AdditionalText)
  nameWithType: AnalyzerConfigOptionsProvider.GetOptions(AdditionalText)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public abstract Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions GetOptions (Microsoft.CodeAnalysis.AdditionalText textFile);
  - lang: fsharp
    values:
    - value: 'abstract member GetOptions : Microsoft.CodeAnalysis.AdditionalText -> Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions'
  - lang: vb
    values:
    - value: Public MustOverride Function GetOptions (textFile As AdditionalText) As AnalyzerConfigOptions
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Get options for a given <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AdditionalText"></xref>
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions?alt=Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions&text=AnalyzerConfigOptions" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: tree
    type: <xref href="Microsoft.CodeAnalysis.SyntaxTree?alt=Microsoft.CodeAnalysis.SyntaxTree&text=SyntaxTree" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions(Microsoft.CodeAnalysis.SyntaxTree)
  commentId: M:Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions(Microsoft.CodeAnalysis.SyntaxTree)
  name: GetOptions(SyntaxTree)
  fullName: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions(SyntaxTree)
  nameWithType: AnalyzerConfigOptionsProvider.GetOptions(SyntaxTree)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public abstract Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions GetOptions (Microsoft.CodeAnalysis.SyntaxTree tree);
  - lang: fsharp
    values:
    - value: 'abstract member GetOptions : Microsoft.CodeAnalysis.SyntaxTree -> Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions'
  - lang: vb
    values:
    - value: Public MustOverride Function GetOptions (tree As SyntaxTree) As AnalyzerConfigOptions
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Get options for a given <code data-dev-comment-type="paramref">tree</code>.
  metadata: {}
uid: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions*
commentId: Overload:Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions
namespace: Microsoft.CodeAnalysis.Diagnostics
name: GetOptions
fullName: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions
nameWithType: AnalyzerConfigOptionsProvider.GetOptions
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GetOptions
  - Microsoft::CodeAnalysis::Diagnostics::AnalyzerConfigOptionsProvider::GetOptions
  - GetOptions
  - AnalyzerConfigOptionsProvider.GetOptions
  - AnalyzerConfigOptionsProvider::GetOptions
  helpviewer_keywords:
  - AnalyzerConfigOptionsProvider.GetOptions method [.NET]
  - GetOptions method [.NET], class AnalyzerConfigOptionsProvider
  - AnalyzerConfigOptionsProvider.GetOptions(AdditionalText) method [.NET]
  - GetOptions(AdditionalText) method [.NET], class AnalyzerConfigOptionsProvider
  - AnalyzerConfigOptionsProvider.GetOptions(SyntaxTree) method [.NET]
  - GetOptions(SyntaxTree) method [.NET], class AnalyzerConfigOptionsProvider
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
