### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory
  name: NormalizedDirectory
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory
  nameWithType: AnalyzerConfig.NormalizedDirectory
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string NormalizedDirectory { get; }
  - lang: fsharp
    values:
    - value: 'member this.NormalizedDirectory : string'
  - lang: vb
    values:
    - value: Public ReadOnly Property NormalizedDirectory As String
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: >-
    The directory the editorconfig was contained in, with all directory separators

    replaced with '/'.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory
namespace: Microsoft.CodeAnalysis
name: NormalizedDirectory
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory
nameWithType: AnalyzerConfig.NormalizedDirectory
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory
  - Microsoft.CodeAnalysis.AnalyzerConfig.get_NormalizedDirectory
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.NormalizedDirectory
  - Microsoft::CodeAnalysis::AnalyzerConfig::NormalizedDirectory
  - NormalizedDirectory
  - AnalyzerConfig.NormalizedDirectory
  - AnalyzerConfig::NormalizedDirectory
  helpviewer_keywords:
  - AnalyzerConfig.NormalizedDirectory property [.NET]
  - NormalizedDirectory property [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
