### YamlMime:NetMember
type: method
members:
- typeParameters:
  - name: TList
  returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfigSet?alt=Microsoft.CodeAnalysis.AnalyzerConfigSet&text=AnalyzerConfigSet" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: analyzerConfigs
    type: TList
  type: method
  uid: Microsoft.CodeAnalysis.AnalyzerConfigSet.Create``1(``0)
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfigSet.Create``1(``0)
  name: Create<TList>(TList)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfigSet.Create<TList>(TList)
  nameWithType: AnalyzerConfigSet.Create<TList>(TList)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: 'public static Microsoft.CodeAnalysis.AnalyzerConfigSet Create<TList> (TList analyzerConfigs) where TList : System.Collections.Generic.IReadOnlyCollection<Microsoft.CodeAnalysis.AnalyzerConfig>;'
  - lang: fsharp
    values:
    - value: "static member Create : 'List -> Microsoft.CodeAnalysis.AnalyzerConfigSet (requires 'List :> System.Collections.Generic.IReadOnlyCollection<Microsoft.CodeAnalysis.AnalyzerConfig>)"
  - lang: vb
    values:
    - value: Public Shared Function Create(Of TList As IReadOnlyCollection(Of AnalyzerConfig)) (analyzerConfigs As TList) As AnalyzerConfigSet
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  metadata: {}
- typeParameters:
  - name: TList
  returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfigSet?alt=Microsoft.CodeAnalysis.AnalyzerConfigSet&text=AnalyzerConfigSet" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: analyzerConfigs
    type: TList
  - namesWithMoniker:
    - value: diagnostics
    type: <xref href="System.Collections.Immutable.ImmutableArray`1?alt=System.Collections.Immutable.ImmutableArray&text=ImmutableArray" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.Diagnostic?alt=Microsoft.CodeAnalysis.Diagnostic&text=Diagnostic" data-throw-if-not-resolved="True"/>&gt;
  type: method
  uid: Microsoft.CodeAnalysis.AnalyzerConfigSet.Create``1(``0,System.Collections.Immutable.ImmutableArray{Microsoft.CodeAnalysis.Diagnostic}@)
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfigSet.Create``1(``0,System.Collections.Immutable.ImmutableArray{Microsoft.CodeAnalysis.Diagnostic}@)
  name: Create<TList>(TList, ImmutableArray<Diagnostic>)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfigSet.Create<TList>(TList, ImmutableArray<Diagnostic>)
  nameWithType: AnalyzerConfigSet.Create<TList>(TList, ImmutableArray<Diagnostic>)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: 'public static Microsoft.CodeAnalysis.AnalyzerConfigSet Create<TList> (TList analyzerConfigs, out System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic> diagnostics) where TList : System.Collections.Generic.IReadOnlyCollection<Microsoft.CodeAnalysis.AnalyzerConfig>;'
  - lang: fsharp
    values:
    - value: "static member Create : 'List * ImmutableArray -> Microsoft.CodeAnalysis.AnalyzerConfigSet (requires 'List :> System.Collections.Generic.IReadOnlyCollection<Microsoft.CodeAnalysis.AnalyzerConfig>)"
  - lang: vb
    values:
    - value: Public Shared Function Create(Of TList As IReadOnlyCollection(Of AnalyzerConfig)) (analyzerConfigs As TList, ByRef diagnostics As ImmutableArray(Of Diagnostic)) As AnalyzerConfigSet
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfigSet.Create*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfigSet.Create
namespace: Microsoft.CodeAnalysis
name: Create
fullName: Microsoft.CodeAnalysis.AnalyzerConfigSet.Create
nameWithType: AnalyzerConfigSet.Create
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.Create
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.Create
  - Microsoft::CodeAnalysis::AnalyzerConfigSet::Create
  - Create
  - AnalyzerConfigSet.Create
  - AnalyzerConfigSet::Create
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.Create``1
  - Microsoft::CodeAnalysis::AnalyzerConfigSet::Create``1
  - Create``1
  - AnalyzerConfigSet.Create``1
  - AnalyzerConfigSet::Create``1
  helpviewer_keywords:
  - AnalyzerConfigSet.Create method [.NET]
  - Create method [.NET], class AnalyzerConfigSet
  - AnalyzerConfigSet.Create<TList>(TList) method [.NET]
  - Create<TList>(TList) method [.NET], class AnalyzerConfigSet
  - AnalyzerConfigSet.Create<TList>(TList, ImmutableArray<Diagnostic>) method [.NET]
  - Create<TList>(TList, ImmutableArray<Diagnostic>) method [.NET], class AnalyzerConfigSet
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
