### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Solution?alt=Microsoft.CodeAnalysis.Solution&text=Solution" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: loader
    type: <xref href="Microsoft.CodeAnalysis.TextLoader?alt=Microsoft.CodeAnalysis.TextLoader&text=TextLoader" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: mode
    type: <xref href="Microsoft.CodeAnalysis.PreservationMode?alt=Microsoft.CodeAnalysis.PreservationMode&text=PreservationMode" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.TextLoader,Microsoft.CodeAnalysis.PreservationMode)
  commentId: M:Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.TextLoader,Microsoft.CodeAnalysis.PreservationMode)
  name: WithAnalyzerConfigDocumentTextLoader(DocumentId, TextLoader, PreservationMode)
  fullName: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader(DocumentId, TextLoader, PreservationMode)
  nameWithType: Solution.WithAnalyzerConfigDocumentTextLoader(DocumentId, TextLoader, PreservationMode)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.Solution WithAnalyzerConfigDocumentTextLoader (Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.TextLoader loader, Microsoft.CodeAnalysis.PreservationMode mode);
  - lang: fsharp
    values:
    - value: 'member this.WithAnalyzerConfigDocumentTextLoader : Microsoft.CodeAnalysis.DocumentId * Microsoft.CodeAnalysis.TextLoader * Microsoft.CodeAnalysis.PreservationMode -> Microsoft.CodeAnalysis.Solution'
  - lang: vb
    values:
    - value: Public Function WithAnalyzerConfigDocumentTextLoader (documentId As DocumentId, loader As TextLoader, mode As PreservationMode) As Solution
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Creates a new solution instance with the analyzer config document specified updated to have the text

    supplied by the text loader.
  metadata: {}
uid: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader*
commentId: Overload:Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader
namespace: Microsoft.CodeAnalysis
name: WithAnalyzerConfigDocumentTextLoader
fullName: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader
nameWithType: Solution.WithAnalyzerConfigDocumentTextLoader
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentTextLoader
  - Microsoft::CodeAnalysis::Solution::WithAnalyzerConfigDocumentTextLoader
  - WithAnalyzerConfigDocumentTextLoader
  - Solution.WithAnalyzerConfigDocumentTextLoader
  - Solution::WithAnalyzerConfigDocumentTextLoader
  helpviewer_keywords:
  - Solution.WithAnalyzerConfigDocumentTextLoader method [.NET]
  - WithAnalyzerConfigDocumentTextLoader method [.NET], class Solution
  - Solution.WithAnalyzerConfigDocumentTextLoader(DocumentId, TextLoader, PreservationMode) method [.NET]
  - WithAnalyzerConfigDocumentTextLoader(DocumentId, TextLoader, PreservationMode) method [.NET], class Solution
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
