### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: analysisMode
    type: <xref href="Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags?alt=Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags&text=GeneratedCodeAnalysisFlags" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis(Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags)
  commentId: M:Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis(Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags)
  name: ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags)
  fullName: Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags)
  nameWithType: AnalysisContext.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags)
  syntaxWithMoniker:
  - lang: cpp
    values:
    - value: >-
        public:
         virtual void ConfigureGeneratedCodeAnalysis(Microsoft::CodeAnalysis::Diagnostics::GeneratedCodeAnalysisFlags analysisMode);
  - lang: csharp
    values:
    - value: public virtual void ConfigureGeneratedCodeAnalysis (Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags analysisMode);
  - lang: fsharp
    values:
    - value: >-
        abstract member ConfigureGeneratedCodeAnalysis : Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags -> unit

        override this.ConfigureGeneratedCodeAnalysis : Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags -> unit
  - lang: vb
    values:
    - value: Public Overridable Sub ConfigureGeneratedCodeAnalysis (analysisMode As GeneratedCodeAnalysisFlags)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.0
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Configure analysis mode of generated code for this analyzer.

    Non-configured analyzers will default to an appropriate default mode for generated code.

    It is recommended for the analyzer to invoke this API with the required <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags"></xref> setting.
  metadata: {}
uid: Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis*
commentId: Overload:Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis
namespace: Microsoft.CodeAnalysis.Diagnostics
name: ConfigureGeneratedCodeAnalysis
fullName: Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis
nameWithType: AnalysisContext.ConfigureGeneratedCodeAnalysis
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.0.0
  monikers:
  - roslyn-dotnet-3.0
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- cpp
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.0
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.ConfigureGeneratedCodeAnalysis
  - Microsoft::CodeAnalysis::Diagnostics::AnalysisContext::ConfigureGeneratedCodeAnalysis
  - ConfigureGeneratedCodeAnalysis
  - AnalysisContext.ConfigureGeneratedCodeAnalysis
  - AnalysisContext::ConfigureGeneratedCodeAnalysis
  helpviewer_keywords:
  - AnalysisContext.ConfigureGeneratedCodeAnalysis method [.NET]
  - ConfigureGeneratedCodeAnalysis method [.NET], class AnalysisContext
  - AnalysisContext.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags) method [.NET]
  - ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags) method [.NET], class AnalysisContext
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.0
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
