### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot
  name: IsRoot
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot
  nameWithType: AnalyzerConfig.IsRoot
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsRoot { get; }
  - lang: fsharp
    values:
    - value: 'member this.IsRoot : bool'
  - lang: vb
    values:
    - value: Public ReadOnly Property IsRoot As Boolean
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: Gets whether this editorconfig is a topmost editorconfig.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot
namespace: Microsoft.CodeAnalysis
name: IsRoot
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot
nameWithType: AnalyzerConfig.IsRoot
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot
  - Microsoft.CodeAnalysis.AnalyzerConfig.get_IsRoot
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.IsRoot
  - Microsoft::CodeAnalysis::AnalyzerConfig::IsRoot
  - IsRoot
  - AnalyzerConfig.IsRoot
  - AnalyzerConfig::IsRoot
  helpviewer_keywords:
  - AnalyzerConfig.IsRoot property [.NET]
  - IsRoot property [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
