### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Nullable`1?alt=System.Nullable&text=Nullable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher?alt=Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher&text=SectionNameMatcher" data-throw-if-not-resolved="True"/>&gt;
      monikers:
      - roslyn-dotnet-3.1
      - roslyn-dotnet-3.2
      - roslyn-dotnet-3.2.1
      - roslyn-dotnet-3.3.1
  parameters:
  - namesWithMoniker:
    - value: sectionName
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher(System.String)
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher(System.String)
  name: TryCreateSectionNameMatcher(String)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher(String)
  nameWithType: AnalyzerConfig.TryCreateSectionNameMatcher(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher? TryCreateSectionNameMatcher (string sectionName);
  - lang: fsharp
    values:
    - value: 'static member TryCreateSectionNameMatcher : string -> Nullable<Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher>'
  - lang: vb
    values:
    - value: Public Shared Function TryCreateSectionNameMatcher (sectionName As String) As Nullable(Of AnalyzerConfig.SectionNameMatcher)
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: >-
    Takes a <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfig.Section.Name"></xref> and creates a matcher that

    matches the the given language. Returns null if the section name is

    invalid.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher
namespace: Microsoft.CodeAnalysis
name: TryCreateSectionNameMatcher
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher
nameWithType: AnalyzerConfig.TryCreateSectionNameMatcher
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.TryCreateSectionNameMatcher
  - Microsoft::CodeAnalysis::AnalyzerConfig::TryCreateSectionNameMatcher
  - TryCreateSectionNameMatcher
  - AnalyzerConfig.TryCreateSectionNameMatcher
  - AnalyzerConfig::TryCreateSectionNameMatcher
  helpviewer_keywords:
  - AnalyzerConfig.TryCreateSectionNameMatcher method [.NET]
  - TryCreateSectionNameMatcher method [.NET], class AnalyzerConfig
  - AnalyzerConfig.TryCreateSectionNameMatcher(String) method [.NET]
  - TryCreateSectionNameMatcher(String) method [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
