### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: s
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch(System.String)
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch(System.String)
  name: IsMatch(String)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch(String)
  nameWithType: AnalyzerConfig.SectionNameMatcher.IsMatch(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public bool IsMatch (string s);
  - lang: fsharp
    values:
    - value: 'member this.IsMatch : string -> bool'
  - lang: vb
    values:
    - value: Public Function IsMatch (s As String) As Boolean
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch
namespace: Microsoft.CodeAnalysis
name: IsMatch
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch
nameWithType: AnalyzerConfig.SectionNameMatcher.IsMatch
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch
  - Microsoft::CodeAnalysis::AnalyzerConfig::SectionNameMatcher::IsMatch
  - IsMatch
  - SectionNameMatcher.IsMatch
  - SectionNameMatcher::IsMatch
  helpviewer_keywords:
  - AnalyzerConfig.SectionNameMatcher.IsMatch method [.NET]
  - IsMatch method [.NET], struct AnalyzerConfig.SectionNameMatcher
  - AnalyzerConfig.SectionNameMatcher.IsMatch(String) method [.NET]
  - IsMatch(String) method [.NET], struct AnalyzerConfig.SectionNameMatcher
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
