### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId)
  commentId: M:Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId)
  name: CloseAnalyzerConfigDocument(DocumentId)
  fullName: Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument(DocumentId)
  nameWithType: Workspace.CloseAnalyzerConfigDocument(DocumentId)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public virtual void CloseAnalyzerConfigDocument (Microsoft.CodeAnalysis.DocumentId documentId);
  - lang: fsharp
    values:
    - value: >-
        abstract member CloseAnalyzerConfigDocument : Microsoft.CodeAnalysis.DocumentId -> unit

        override this.CloseAnalyzerConfigDocument : Microsoft.CodeAnalysis.DocumentId -> unit
  - lang: vb
    values:
    - value: Public Overridable Sub CloseAnalyzerConfigDocument (documentId As DocumentId)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Close the specified analyzer config document in the host environment.
  metadata: {}
uid: Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument*
commentId: Overload:Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument
namespace: Microsoft.CodeAnalysis
name: CloseAnalyzerConfigDocument
fullName: Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument
nameWithType: Workspace.CloseAnalyzerConfigDocument
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Workspace.CloseAnalyzerConfigDocument
  - Microsoft::CodeAnalysis::Workspace::CloseAnalyzerConfigDocument
  - CloseAnalyzerConfigDocument
  - Workspace.CloseAnalyzerConfigDocument
  - Workspace::CloseAnalyzerConfigDocument
  helpviewer_keywords:
  - Workspace.CloseAnalyzerConfigDocument method [.NET]
  - CloseAnalyzerConfigDocument method [.NET], class Workspace
  - Workspace.CloseAnalyzerConfigDocument(DocumentId) method [.NET]
  - CloseAnalyzerConfigDocument(DocumentId) method [.NET], class Workspace
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
