### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: info
    type: <xref href="Microsoft.CodeAnalysis.DocumentInfo?alt=Microsoft.CodeAnalysis.DocumentInfo&text=DocumentInfo" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: text
    type: <xref href="Microsoft.CodeAnalysis.Text.SourceText?alt=Microsoft.CodeAnalysis.Text.SourceText&text=SourceText" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded(Microsoft.CodeAnalysis.DocumentInfo,Microsoft.CodeAnalysis.Text.SourceText)
  commentId: M:Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded(Microsoft.CodeAnalysis.DocumentInfo,Microsoft.CodeAnalysis.Text.SourceText)
  name: ApplyAnalyzerConfigDocumentAdded(DocumentInfo, SourceText)
  fullName: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded(DocumentInfo, SourceText)
  nameWithType: Workspace.ApplyAnalyzerConfigDocumentAdded(DocumentInfo, SourceText)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected virtual void ApplyAnalyzerConfigDocumentAdded (Microsoft.CodeAnalysis.DocumentInfo info, Microsoft.CodeAnalysis.Text.SourceText text);
  - lang: fsharp
    values:
    - value: >-
        abstract member ApplyAnalyzerConfigDocumentAdded : Microsoft.CodeAnalysis.DocumentInfo * Microsoft.CodeAnalysis.Text.SourceText -> unit

        override this.ApplyAnalyzerConfigDocumentAdded : Microsoft.CodeAnalysis.DocumentInfo * Microsoft.CodeAnalysis.Text.SourceText -> unit
  - lang: vb
    values:
    - value: Protected Overridable Sub ApplyAnalyzerConfigDocumentAdded (info As DocumentInfo, text As SourceText)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    This method is called during <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Microsoft.CodeAnalysis.Solution)"></xref> to add a new analyzer config document to a project.


    Override this method to implement the capability of adding analyzer config documents.
  metadata: {}
uid: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded*
commentId: Overload:Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded
namespace: Microsoft.CodeAnalysis
name: ApplyAnalyzerConfigDocumentAdded
fullName: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded
nameWithType: Workspace.ApplyAnalyzerConfigDocumentAdded
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentAdded
  - Microsoft::CodeAnalysis::Workspace::ApplyAnalyzerConfigDocumentAdded
  - ApplyAnalyzerConfigDocumentAdded
  - Workspace.ApplyAnalyzerConfigDocumentAdded
  - Workspace::ApplyAnalyzerConfigDocumentAdded
  helpviewer_keywords:
  - Workspace.ApplyAnalyzerConfigDocumentAdded method [.NET]
  - ApplyAnalyzerConfigDocumentAdded method [.NET], class Workspace
  - Workspace.ApplyAnalyzerConfigDocumentAdded(DocumentInfo, SourceText) method [.NET]
  - ApplyAnalyzerConfigDocumentAdded(DocumentInfo, SourceText) method [.NET], class Workspace
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
