### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Project?alt=Microsoft.CodeAnalysis.Project&text=Project" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId)
  commentId: M:Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId)
  name: RemoveAnalyzerConfigDocument(DocumentId)
  fullName: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument(DocumentId)
  nameWithType: Project.RemoveAnalyzerConfigDocument(DocumentId)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.Project RemoveAnalyzerConfigDocument (Microsoft.CodeAnalysis.DocumentId documentId);
  - lang: fsharp
    values:
    - value: 'member this.RemoveAnalyzerConfigDocument : Microsoft.CodeAnalysis.DocumentId -> Microsoft.CodeAnalysis.Project'
  - lang: vb
    values:
    - value: Public Function RemoveAnalyzerConfigDocument (documentId As DocumentId) As Project
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Creates a new instance of this project updated to no longer include the specified analyzer config document.
  metadata: {}
uid: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument*
commentId: Overload:Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument
namespace: Microsoft.CodeAnalysis
name: RemoveAnalyzerConfigDocument
fullName: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument
nameWithType: Project.RemoveAnalyzerConfigDocument
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocument
  - Microsoft::CodeAnalysis::Project::RemoveAnalyzerConfigDocument
  - RemoveAnalyzerConfigDocument
  - Project.RemoveAnalyzerConfigDocument
  - Project::RemoveAnalyzerConfigDocument
  helpviewer_keywords:
  - Project.RemoveAnalyzerConfigDocument method [.NET]
  - RemoveAnalyzerConfigDocument method [.NET], class Project
  - Project.RemoveAnalyzerConfigDocument(DocumentId) method [.NET]
  - RemoveAnalyzerConfigDocument(DocumentId) method [.NET], class Project
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
