### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: activate
    type: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId,System.Boolean)
  commentId: M:Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId,System.Boolean)
  name: OpenAnalyzerConfigDocument(DocumentId, Boolean)
  fullName: Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument(DocumentId, Boolean)
  nameWithType: AdhocWorkspace.OpenAnalyzerConfigDocument(DocumentId, Boolean)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public override void OpenAnalyzerConfigDocument (Microsoft.CodeAnalysis.DocumentId documentId, bool activate = true);
  - lang: fsharp
    values:
    - value: 'override this.OpenAnalyzerConfigDocument : Microsoft.CodeAnalysis.DocumentId * bool -> unit'
  - lang: vb
    values:
    - value: Public Overrides Sub OpenAnalyzerConfigDocument (documentId As DocumentId, Optional activate As Boolean = true)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Puts the specified analyzer config document into the open state.
  metadata: {}
uid: Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument*
commentId: Overload:Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument
namespace: Microsoft.CodeAnalysis
name: OpenAnalyzerConfigDocument
fullName: Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument
nameWithType: AdhocWorkspace.OpenAnalyzerConfigDocument
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AdhocWorkspace.OpenAnalyzerConfigDocument
  - Microsoft::CodeAnalysis::AdhocWorkspace::OpenAnalyzerConfigDocument
  - OpenAnalyzerConfigDocument
  - AdhocWorkspace.OpenAnalyzerConfigDocument
  - AdhocWorkspace::OpenAnalyzerConfigDocument
  helpviewer_keywords:
  - AdhocWorkspace.OpenAnalyzerConfigDocument method [.NET]
  - OpenAnalyzerConfigDocument method [.NET], class AdhocWorkspace
  - AdhocWorkspace.OpenAnalyzerConfigDocument(DocumentId, Boolean) method [.NET]
  - OpenAnalyzerConfigDocument(DocumentId, Boolean) method [.NET], class AdhocWorkspace
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
