### YamlMime:NetType
type: struct
inheritancesWithMoniker:
- values:
  - <xref href="System.ValueType?alt=System.ValueType&text=ValueType" data-throw-if-not-resolved="True"/>
methods:
- uid: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher.IsMatch(System.String)
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
uid: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher
commentId: T:Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfig.SectionNameMatcher
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher
nameWithType: Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public readonly struct AnalyzerConfig.SectionNameMatcher
- lang: fsharp
  values:
  - value: type AnalyzerConfig.SectionNameMatcher = struct
- lang: vb
  values:
  - value: Public Structure AnalyzerConfig.SectionNameMatcher
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher
  - Microsoft::CodeAnalysis::AnalyzerConfig::SectionNameMatcher
  - SectionNameMatcher
  helpviewer_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.SectionNameMatcher struct [.NET]
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
