### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.AnalyzerConfigDocument?alt=Microsoft.CodeAnalysis.AnalyzerConfigDocument&text=AnalyzerConfigDocument" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments
  commentId: P:Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments
  name: AnalyzerConfigDocuments
  fullName: Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments
  nameWithType: Project.AnalyzerConfigDocuments
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.AnalyzerConfigDocument> AnalyzerConfigDocuments { get; }
  - lang: fsharp
    values:
    - value: 'member this.AnalyzerConfigDocuments : seq<Microsoft.CodeAnalysis.AnalyzerConfigDocument>'
  - lang: vb
    values:
    - value: Public ReadOnly Property AnalyzerConfigDocuments As IEnumerable(Of AnalyzerConfigDocument)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: All the <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfigDocument"></xref>s associated with this project.
  metadata: {}
uid: Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments*
commentId: Overload:Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfigDocuments
fullName: Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments
nameWithType: Project.AnalyzerConfigDocuments
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments
  - Microsoft.CodeAnalysis.Project.get_AnalyzerConfigDocuments
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Project.AnalyzerConfigDocuments
  - Microsoft::CodeAnalysis::Project::AnalyzerConfigDocuments
  - AnalyzerConfigDocuments
  - Project.AnalyzerConfigDocuments
  - Project::AnalyzerConfigDocuments
  helpviewer_keywords:
  - Project.AnalyzerConfigDocuments property [.NET]
  - AnalyzerConfigDocuments property [.NET], class Project
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
