### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult?alt=Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult&text=AnalyzerConfigOptionsResult" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: sourcePath
    description: The path to a file such as a source file or additional file. Must be non-null.
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath(System.String)
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath(System.String)
  name: GetOptionsForSourcePath(String)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath(String)
  nameWithType: AnalyzerConfigSet.GetOptionsForSourcePath(String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult GetOptionsForSourcePath (string sourcePath);
  - lang: fsharp
    values:
    - value: 'member this.GetOptionsForSourcePath : string -> Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult'
  - lang: vb
    values:
    - value: Public Function GetOptionsForSourcePath (sourcePath As String) As AnalyzerConfigOptionsResult
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Returns a <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult"></xref> for a source file. This computes which <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfig"></xref> rules applies to this file, and correctly applies

    precedence rules if there are multiple rules for the same file.
  remarks: This method is safe to call from multiple threads.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath
namespace: Microsoft.CodeAnalysis
name: GetOptionsForSourcePath
fullName: Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath
nameWithType: AnalyzerConfigSet.GetOptionsForSourcePath
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath
  - Microsoft::CodeAnalysis::AnalyzerConfigSet::GetOptionsForSourcePath
  - GetOptionsForSourcePath
  - AnalyzerConfigSet.GetOptionsForSourcePath
  - AnalyzerConfigSet::GetOptionsForSourcePath
  helpviewer_keywords:
  - AnalyzerConfigSet.GetOptionsForSourcePath method [.NET]
  - GetOptionsForSourcePath method [.NET], class AnalyzerConfigSet
  - AnalyzerConfigSet.GetOptionsForSourcePath(String) method [.NET]
  - GetOptionsForSourcePath(String) method [.NET], class AnalyzerConfigSet
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
