### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution(Microsoft.CodeAnalysis.DocumentId)
  commentId: M:Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution(Microsoft.CodeAnalysis.DocumentId)
  name: CheckAnalyzerConfigDocumentIsInCurrentSolution(DocumentId)
  fullName: Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution(DocumentId)
  nameWithType: Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution(DocumentId)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected void CheckAnalyzerConfigDocumentIsInCurrentSolution (Microsoft.CodeAnalysis.DocumentId documentId);
  - lang: fsharp
    values:
    - value: 'member this.CheckAnalyzerConfigDocumentIsInCurrentSolution : Microsoft.CodeAnalysis.DocumentId -> unit'
  - lang: vb
    values:
    - value: Protected Sub CheckAnalyzerConfigDocumentIsInCurrentSolution (documentId As DocumentId)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Throws an exception if an analyzer config is not part of the current solution.
  metadata: {}
uid: Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution*
commentId: Overload:Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution
namespace: Microsoft.CodeAnalysis
name: CheckAnalyzerConfigDocumentIsInCurrentSolution
fullName: Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution
nameWithType: Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution
  - Microsoft::CodeAnalysis::Workspace::CheckAnalyzerConfigDocumentIsInCurrentSolution
  - CheckAnalyzerConfigDocumentIsInCurrentSolution
  - Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution
  - Workspace::CheckAnalyzerConfigDocumentIsInCurrentSolution
  helpviewer_keywords:
  - Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution method [.NET]
  - CheckAnalyzerConfigDocumentIsInCurrentSolution method [.NET], class Workspace
  - Workspace.CheckAnalyzerConfigDocumentIsInCurrentSolution(DocumentId) method [.NET]
  - CheckAnalyzerConfigDocumentIsInCurrentSolution(DocumentId) method [.NET], class Workspace
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
