### YamlMime:NetMember
type: method
members:
- parameters:
  - namesWithMoniker:
    - value: id
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: text
    type: <xref href="Microsoft.CodeAnalysis.Text.SourceText?alt=Microsoft.CodeAnalysis.Text.SourceText&text=SourceText" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.Text.SourceText)
  commentId: M:Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.Text.SourceText)
  name: ApplyAnalyzerConfigDocumentTextChanged(DocumentId, SourceText)
  fullName: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged(DocumentId, SourceText)
  nameWithType: Workspace.ApplyAnalyzerConfigDocumentTextChanged(DocumentId, SourceText)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: protected virtual void ApplyAnalyzerConfigDocumentTextChanged (Microsoft.CodeAnalysis.DocumentId id, Microsoft.CodeAnalysis.Text.SourceText text);
  - lang: fsharp
    values:
    - value: >-
        abstract member ApplyAnalyzerConfigDocumentTextChanged : Microsoft.CodeAnalysis.DocumentId * Microsoft.CodeAnalysis.Text.SourceText -> unit

        override this.ApplyAnalyzerConfigDocumentTextChanged : Microsoft.CodeAnalysis.DocumentId * Microsoft.CodeAnalysis.Text.SourceText -> unit
  - lang: vb
    values:
    - value: Protected Overridable Sub ApplyAnalyzerConfigDocumentTextChanged (id As DocumentId, text As SourceText)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    This method is called to change the text of an analyzer config document.


    Override this method to implement the capability of changing analyzer config document text.
  metadata: {}
uid: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged*
commentId: Overload:Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged
namespace: Microsoft.CodeAnalysis
name: ApplyAnalyzerConfigDocumentTextChanged
fullName: Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged
nameWithType: Workspace.ApplyAnalyzerConfigDocumentTextChanged
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Workspace.ApplyAnalyzerConfigDocumentTextChanged
  - Microsoft::CodeAnalysis::Workspace::ApplyAnalyzerConfigDocumentTextChanged
  - ApplyAnalyzerConfigDocumentTextChanged
  - Workspace.ApplyAnalyzerConfigDocumentTextChanged
  - Workspace::ApplyAnalyzerConfigDocumentTextChanged
  helpviewer_keywords:
  - Workspace.ApplyAnalyzerConfigDocumentTextChanged method [.NET]
  - ApplyAnalyzerConfigDocumentTextChanged method [.NET], class Workspace
  - Workspace.ApplyAnalyzerConfigDocumentTextChanged(DocumentId, SourceText) method [.NET]
  - ApplyAnalyzerConfigDocumentTextChanged(DocumentId, SourceText) method [.NET], class Workspace
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
