### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IEnumerable`1?alt=System.Collections.Generic.IEnumerable&text=IEnumerable" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>&gt;
  type: method
  uid: Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments
  commentId: M:Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments
  name: GetAddedAnalyzerConfigDocuments()
  fullName: Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments()
  nameWithType: ProjectChanges.GetAddedAnalyzerConfigDocuments()
  attributesWithMoniker:
  - value: System.Runtime.CompilerServices.IteratorStateMachineAttribute
    monikers:
    - roslyn-dotnet-3.2
    - roslyn-dotnet-3.2.1
    - roslyn-dotnet-3.3.1
    - roslyn-dotnet-3.4.0
    - roslyn-dotnet-3.5.0
    - roslyn-dotnet-3.6.0
    - roslyn-dotnet-3.7.0
    - roslyn-dotnet-3.8.0
    - roslyn-dotnet-3.9.0
  attributeMonikers:
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.DocumentId> GetAddedAnalyzerConfigDocuments ();
      monikers:
      - roslyn-dotnet
      - roslyn-dotnet-3.10.0
      - roslyn-dotnet-3.11.0
      - roslyn-dotnet-4.0.1
      - roslyn-dotnet-4.1.0
      - roslyn-dotnet-4.2.0
    - value: >-
        [System.Runtime.CompilerServices.IteratorStateMachine(typeof(Microsoft.CodeAnalysis.ProjectChanges+<GetAddedAnalyzerConfigDocuments>d__17))]

        public System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.DocumentId> GetAddedAnalyzerConfigDocuments ();
      monikers:
      - roslyn-dotnet-3.2
      - roslyn-dotnet-3.2.1
      - roslyn-dotnet-3.3.1
      - roslyn-dotnet-3.4.0
      - roslyn-dotnet-3.5.0
      - roslyn-dotnet-3.6.0
      - roslyn-dotnet-3.7.0
      - roslyn-dotnet-3.8.0
      - roslyn-dotnet-3.9.0
  - lang: fsharp
    values:
    - value: 'member this.GetAddedAnalyzerConfigDocuments : unit -> seq<Microsoft.CodeAnalysis.DocumentId>'
      monikers:
      - roslyn-dotnet
      - roslyn-dotnet-3.10.0
      - roslyn-dotnet-3.11.0
      - roslyn-dotnet-4.0.1
      - roslyn-dotnet-4.1.0
      - roslyn-dotnet-4.2.0
    - value: >-
        [<System.Runtime.CompilerServices.IteratorStateMachine(typeof(Microsoft.CodeAnalysis.ProjectChanges+<GetAddedAnalyzerConfigDocuments>d__17))>]

        member this.GetAddedAnalyzerConfigDocuments : unit -> seq<Microsoft.CodeAnalysis.DocumentId>
      monikers:
      - roslyn-dotnet-3.2
      - roslyn-dotnet-3.2.1
      - roslyn-dotnet-3.3.1
      - roslyn-dotnet-3.4.0
      - roslyn-dotnet-3.5.0
      - roslyn-dotnet-3.6.0
      - roslyn-dotnet-3.7.0
      - roslyn-dotnet-3.8.0
      - roslyn-dotnet-3.9.0
  - lang: vb
    values:
    - value: Public Function GetAddedAnalyzerConfigDocuments () As IEnumerable(Of DocumentId)
      monikers:
      - roslyn-dotnet-3.10.0
      - roslyn-dotnet-3.11.0
      - roslyn-dotnet-4.0.1
      - roslyn-dotnet-4.1.0
      - roslyn-dotnet-4.2.0
    - value: Public Iterator Function GetAddedAnalyzerConfigDocuments () As IEnumerable(Of DocumentId)
      monikers:
      - roslyn-dotnet-3.2
      - roslyn-dotnet-3.2.1
      - roslyn-dotnet-3.3.1
      - roslyn-dotnet-3.4.0
      - roslyn-dotnet-3.5.0
      - roslyn-dotnet-3.6.0
      - roslyn-dotnet-3.7.0
      - roslyn-dotnet-3.8.0
      - roslyn-dotnet-3.9.0
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Get <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.DocumentId"></xref>s of added analyzer config documents in the order they appear in <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.Project.DocumentIds"></xref> of <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.ProjectChanges.NewProject"></xref>.
  metadata: {}
uid: Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments*
commentId: Overload:Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments
namespace: Microsoft.CodeAnalysis
name: GetAddedAnalyzerConfigDocuments
fullName: Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments
nameWithType: ProjectChanges.GetAddedAnalyzerConfigDocuments
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.ProjectChanges.GetAddedAnalyzerConfigDocuments
  - Microsoft::CodeAnalysis::ProjectChanges::GetAddedAnalyzerConfigDocuments
  - GetAddedAnalyzerConfigDocuments
  - ProjectChanges.GetAddedAnalyzerConfigDocuments
  - ProjectChanges::GetAddedAnalyzerConfigDocuments
  helpviewer_keywords:
  - ProjectChanges.GetAddedAnalyzerConfigDocuments method [.NET]
  - GetAddedAnalyzerConfigDocuments method [.NET], struct ProjectChanges
  - ProjectChanges.GetAddedAnalyzerConfigDocuments() method [.NET]
  - GetAddedAnalyzerConfigDocuments() method [.NET], struct ProjectChanges
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
