### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult?alt=Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult&text=AnalyzerConfigOptionsResult" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions
  name: GlobalConfigOptions
  fullName: Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions
  nameWithType: AnalyzerConfigSet.GlobalConfigOptions
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult GlobalConfigOptions { get; }
  - lang: fsharp
    values:
    - value: 'member this.GlobalConfigOptions : Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult'
  - lang: vb
    values:
    - value: Public ReadOnly Property GlobalConfigOptions As AnalyzerConfigOptionsResult
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Gets an <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult"></xref> that contain the options that apply globally
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions
namespace: Microsoft.CodeAnalysis
name: GlobalConfigOptions
fullName: Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions
nameWithType: AnalyzerConfigSet.GlobalConfigOptions
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.get_GlobalConfigOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfigSet.GlobalConfigOptions
  - Microsoft::CodeAnalysis::AnalyzerConfigSet::GlobalConfigOptions
  - GlobalConfigOptions
  - AnalyzerConfigSet.GlobalConfigOptions
  - AnalyzerConfigSet::GlobalConfigOptions
  helpviewer_keywords:
  - AnalyzerConfigSet.GlobalConfigOptions property [.NET]
  - GlobalConfigOptions property [.NET], class AnalyzerConfigSet
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
