### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile
  name: PathToFile
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile
  nameWithType: AnalyzerConfig.PathToFile
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public string PathToFile { get; }
  - lang: fsharp
    values:
    - value: 'member this.PathToFile : string'
  - lang: vb
    values:
    - value: Public ReadOnly Property PathToFile As String
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: The path passed to <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfig.Parse(System.String,System.String)"></xref> during construction.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile
namespace: Microsoft.CodeAnalysis
name: PathToFile
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile
nameWithType: AnalyzerConfig.PathToFile
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile
  - Microsoft.CodeAnalysis.AnalyzerConfig.get_PathToFile
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.PathToFile
  - Microsoft::CodeAnalysis::AnalyzerConfig::PathToFile
  - PathToFile
  - AnalyzerConfig.PathToFile
  - AnalyzerConfig::PathToFile
  helpviewer_keywords:
  - AnalyzerConfig.PathToFile property [.NET]
  - PathToFile property [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
