### YamlMime:NetMember
type: constructor
members:
- parameters:
  - namesWithMoniker:
    - value: name
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: properties
    type: <xref href="System.Collections.Immutable.ImmutableDictionary`2?alt=System.Collections.Immutable.ImmutableDictionary&text=ImmutableDictionary" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>,<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: constructor
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.#ctor(System.String,System.Collections.Immutable.ImmutableDictionary{System.String,System.String})
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfig.Section.#ctor(System.String,System.Collections.Immutable.ImmutableDictionary{System.String,System.String})
  name: AnalyzerConfig.Section(String, ImmutableDictionary<String,String>)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.AnalyzerConfig.Section(String, ImmutableDictionary<String,String>)
  nameWithType: AnalyzerConfig.Section.AnalyzerConfig.Section(String, ImmutableDictionary<String,String>)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Section (string name, System.Collections.Immutable.ImmutableDictionary<string,string> properties);
  - lang: fsharp
    values:
    - value: 'new Microsoft.CodeAnalysis.AnalyzerConfig.Section : string * System.Collections.Immutable.ImmutableDictionary<string, string> -> Microsoft.CodeAnalysis.AnalyzerConfig.Section'
  - lang: vb
    values:
    - value: Public Sub New (name As String, properties As ImmutableDictionary(Of String, String))
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.#ctor*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.Section.#ctor
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfig.Section
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.AnalyzerConfig.Section
nameWithType: AnalyzerConfig.Section.AnalyzerConfig.Section
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section..ctor
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.#ctor
  - Microsoft::CodeAnalysis::AnalyzerConfig::Section::#ctor
  - '#ctor'
  - Section.#ctor
  - Section::#ctor
  helpviewer_keywords:
  - AnalyzerConfig.Section class [.NET], constructors
  - AnalyzerConfig.Section(String, ImmutableDictionary<String,String>) class [.NET], constructors
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
