### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Boolean?alt=System.Boolean&text=Boolean" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: oldNode
    type: TNode
  - namesWithMoniker:
    - value: newNode
    type: TNode
  type: method
  uid: Microsoft.CodeAnalysis.Differencing.TreeComparer`1.ValuesEqual(`0,`0)
  commentId: M:Microsoft.CodeAnalysis.Differencing.TreeComparer`1.ValuesEqual(`0,`0)
  name: ValuesEqual(TNode, TNode)
  fullName: Microsoft.CodeAnalysis.Differencing.TreeComparer<TNode>.ValuesEqual(TNode, TNode)
  nameWithType: TreeComparer<TNode>.ValuesEqual(TNode, TNode)
  syntaxWithMoniker:
  - lang: cpp
    values:
    - value: >-
        public:
         abstract bool ValuesEqual(TNode oldNode, TNode newNode);
  - lang: csharp
    values:
    - value: public abstract bool ValuesEqual (TNode oldNode, TNode newNode);
  - lang: fsharp
    values:
    - value: "abstract member ValuesEqual : 'Node * 'Node -> bool"
  - lang: vb
    values:
    - value: Public MustOverride Function ValuesEqual (oldNode As TNode, newNode As TNode) As Boolean
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.0
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Returns true if the specified nodes have equal values.
  remarks: <p>Called with matching nodes (<code data-dev-comment-type="paramref">oldNode</code>, <code data-dev-comment-type="paramref">newNode</code>). Return true if the values of the nodes are the same, or their difference is not important.</p>
  metadata: {}
uid: Microsoft.CodeAnalysis.Differencing.TreeComparer`1.ValuesEqual*
commentId: Overload:Microsoft.CodeAnalysis.Differencing.TreeComparer`1.ValuesEqual
namespace: Microsoft.CodeAnalysis.Differencing
name: ValuesEqual
fullName: Microsoft.CodeAnalysis.Differencing.TreeComparer<TNode>.ValuesEqual
nameWithType: TreeComparer<TNode>.ValuesEqual
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.0.0
  monikers:
  - roslyn-dotnet-3.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- cpp
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.0
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Differencing.TreeComparer`1.ValuesEqual
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Differencing.TreeComparer`1.ValuesEqual
  - Microsoft::CodeAnalysis::Differencing::TreeComparer`1::ValuesEqual
  - Microsoft.CodeAnalysis.Differencing.TreeComparer.ValuesEqual
  - ValuesEqual
  - TreeComparer`1.ValuesEqual
  - TreeComparer`1::ValuesEqual
  helpviewer_keywords:
  - TreeComparer<TNode>.ValuesEqual method [.NET]
  - ValuesEqual method [.NET], class TreeComparer<TNode>
  - TreeComparer<TNode>.ValuesEqual(TNode, TNode) method [.NET]
  - ValuesEqual(TNode, TNode) method [.NET], class TreeComparer<TNode>
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.0
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
