### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Solution?alt=Microsoft.CodeAnalysis.Solution&text=Solution" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: text
    type: <xref href="Microsoft.CodeAnalysis.Text.SourceText?alt=Microsoft.CodeAnalysis.Text.SourceText&text=SourceText" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: mode
    type: <xref href="Microsoft.CodeAnalysis.PreservationMode?alt=Microsoft.CodeAnalysis.PreservationMode&text=PreservationMode" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.Text.SourceText,Microsoft.CodeAnalysis.PreservationMode)
  commentId: M:Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.Text.SourceText,Microsoft.CodeAnalysis.PreservationMode)
  name: WithAnalyzerConfigDocumentText(DocumentId, SourceText, PreservationMode)
  fullName: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText(DocumentId, SourceText, PreservationMode)
  nameWithType: Solution.WithAnalyzerConfigDocumentText(DocumentId, SourceText, PreservationMode)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.Solution WithAnalyzerConfigDocumentText (Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.Text.SourceText text, Microsoft.CodeAnalysis.PreservationMode mode = Microsoft.CodeAnalysis.PreservationMode.PreserveValue);
  - lang: fsharp
    values:
    - value: 'member this.WithAnalyzerConfigDocumentText : Microsoft.CodeAnalysis.DocumentId * Microsoft.CodeAnalysis.Text.SourceText * Microsoft.CodeAnalysis.PreservationMode -> Microsoft.CodeAnalysis.Solution'
  - lang: vb
    values:
    - value: Public Function WithAnalyzerConfigDocumentText (documentId As DocumentId, text As SourceText, Optional mode As PreservationMode = Microsoft.CodeAnalysis.PreservationMode.PreserveValue) As Solution
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Creates a new solution instance with the analyzer config document specified updated to have the text

    supplied by the text loader.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Solution?alt=Microsoft.CodeAnalysis.Solution&text=Solution" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: textAndVersion
    type: <xref href="Microsoft.CodeAnalysis.TextAndVersion?alt=Microsoft.CodeAnalysis.TextAndVersion&text=TextAndVersion" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: mode
    type: <xref href="Microsoft.CodeAnalysis.PreservationMode?alt=Microsoft.CodeAnalysis.PreservationMode&text=PreservationMode" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.TextAndVersion,Microsoft.CodeAnalysis.PreservationMode)
  commentId: M:Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText(Microsoft.CodeAnalysis.DocumentId,Microsoft.CodeAnalysis.TextAndVersion,Microsoft.CodeAnalysis.PreservationMode)
  name: WithAnalyzerConfigDocumentText(DocumentId, TextAndVersion, PreservationMode)
  fullName: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText(DocumentId, TextAndVersion, PreservationMode)
  nameWithType: Solution.WithAnalyzerConfigDocumentText(DocumentId, TextAndVersion, PreservationMode)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.Solution WithAnalyzerConfigDocumentText (Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.TextAndVersion textAndVersion, Microsoft.CodeAnalysis.PreservationMode mode = Microsoft.CodeAnalysis.PreservationMode.PreserveValue);
  - lang: fsharp
    values:
    - value: 'member this.WithAnalyzerConfigDocumentText : Microsoft.CodeAnalysis.DocumentId * Microsoft.CodeAnalysis.TextAndVersion * Microsoft.CodeAnalysis.PreservationMode -> Microsoft.CodeAnalysis.Solution'
  - lang: vb
    values:
    - value: Public Function WithAnalyzerConfigDocumentText (documentId As DocumentId, textAndVersion As TextAndVersion, Optional mode As PreservationMode = Microsoft.CodeAnalysis.PreservationMode.PreserveValue) As Solution
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Creates a new solution instance with the analyzer config document specified updated to have the text

    and version specified.
  metadata: {}
uid: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText*
commentId: Overload:Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText
namespace: Microsoft.CodeAnalysis
name: WithAnalyzerConfigDocumentText
fullName: Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText
nameWithType: Solution.WithAnalyzerConfigDocumentText
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Solution.WithAnalyzerConfigDocumentText
  - Microsoft::CodeAnalysis::Solution::WithAnalyzerConfigDocumentText
  - WithAnalyzerConfigDocumentText
  - Solution.WithAnalyzerConfigDocumentText
  - Solution::WithAnalyzerConfigDocumentText
  helpviewer_keywords:
  - Solution.WithAnalyzerConfigDocumentText method [.NET]
  - WithAnalyzerConfigDocumentText method [.NET], class Solution
  - Solution.WithAnalyzerConfigDocumentText(DocumentId, SourceText, PreservationMode) method [.NET]
  - WithAnalyzerConfigDocumentText(DocumentId, SourceText, PreservationMode) method [.NET], class Solution
  - Solution.WithAnalyzerConfigDocumentText(DocumentId, TextAndVersion, PreservationMode) method [.NET]
  - WithAnalyzerConfigDocumentText(DocumentId, TextAndVersion, PreservationMode) method [.NET], class Solution
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
