### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.IncrementalValueProvider`1?alt=Microsoft.CodeAnalysis.IncrementalValueProvider&text=IncrementalValueProvider" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider?alt=Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider&text=AnalyzerConfigOptionsProvider" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
  commentId: P:Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
  name: AnalyzerConfigOptionsProvider
  fullName: Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
  nameWithType: IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.IncrementalValueProvider<Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider> AnalyzerConfigOptionsProvider { get; }
  - lang: fsharp
    values:
    - value: 'member this.AnalyzerConfigOptionsProvider : Microsoft.CodeAnalysis.IncrementalValueProvider<Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider>'
  - lang: vb
    values:
    - value: Public ReadOnly Property AnalyzerConfigOptionsProvider As IncrementalValueProvider(Of AnalyzerConfigOptionsProvider)
  monikers:
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  metadata: {}
uid: Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider*
commentId: Overload:Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfigOptionsProvider
fullName: Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
nameWithType: IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
  - Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.get_AnalyzerConfigOptionsProvider
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
  - Microsoft::CodeAnalysis::IncrementalGeneratorInitializationContext::AnalyzerConfigOptionsProvider
  - AnalyzerConfigOptionsProvider
  - IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider
  - IncrementalGeneratorInitializationContext::AnalyzerConfigOptionsProvider
  helpviewer_keywords:
  - IncrementalGeneratorInitializationContext.AnalyzerConfigOptionsProvider property [.NET]
  - AnalyzerConfigOptionsProvider property [.NET], struct IncrementalGeneratorInitializationContext
  monikers:
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
