### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.StringComparer?alt=System.StringComparer&text=StringComparer" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
  name: PropertiesKeyComparer
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
  nameWithType: AnalyzerConfig.Section.PropertiesKeyComparer
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static StringComparer PropertiesKeyComparer { get; }
  - lang: fsharp
    values:
    - value: 'member this.PropertiesKeyComparer : StringComparer'
  - lang: vb
    values:
    - value: Public Shared ReadOnly Property PropertiesKeyComparer As StringComparer
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: >-
    Used to compare keys in <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties"></xref>. The editorconfig spec defines property

    keys as being compared case-insensitively according to Unicode lower-case rules.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
namespace: Microsoft.CodeAnalysis
name: PropertiesKeyComparer
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
nameWithType: AnalyzerConfig.Section.PropertiesKeyComparer
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.get_PropertiesKeyComparer
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
  - Microsoft::CodeAnalysis::AnalyzerConfig::Section::PropertiesKeyComparer
  - PropertiesKeyComparer
  - Section.PropertiesKeyComparer
  - Section::PropertiesKeyComparer
  helpviewer_keywords:
  - AnalyzerConfig.Section.PropertiesKeyComparer property [.NET]
  - PropertiesKeyComparer property [.NET], class AnalyzerConfig.Section
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
