### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Generic.IReadOnlyList`1?alt=System.Collections.Generic.IReadOnlyList&text=IReadOnlyList" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.DocumentInfo?alt=Microsoft.CodeAnalysis.DocumentInfo&text=DocumentInfo" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments
  commentId: P:Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments
  name: AnalyzerConfigDocuments
  fullName: Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments
  nameWithType: ProjectInfo.AnalyzerConfigDocuments
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Generic.IReadOnlyList<Microsoft.CodeAnalysis.DocumentInfo> AnalyzerConfigDocuments { get; }
  - lang: fsharp
    values:
    - value: 'member this.AnalyzerConfigDocuments : System.Collections.Generic.IReadOnlyList<Microsoft.CodeAnalysis.DocumentInfo>'
  - lang: vb
    values:
    - value: Public ReadOnly Property AnalyzerConfigDocuments As IReadOnlyList(Of DocumentInfo)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: The list of analyzerconfig documents associated with this project.
  metadata: {}
uid: Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments*
commentId: Overload:Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfigDocuments
fullName: Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments
nameWithType: ProjectInfo.AnalyzerConfigDocuments
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments
  - Microsoft.CodeAnalysis.ProjectInfo.get_AnalyzerConfigDocuments
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.ProjectInfo.AnalyzerConfigDocuments
  - Microsoft::CodeAnalysis::ProjectInfo::AnalyzerConfigDocuments
  - AnalyzerConfigDocuments
  - ProjectInfo.AnalyzerConfigDocuments
  - ProjectInfo::AnalyzerConfigDocuments
  helpviewer_keywords:
  - ProjectInfo.AnalyzerConfigDocuments property [.NET]
  - AnalyzerConfigDocuments property [.NET], class ProjectInfo
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
