### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfig?alt=Microsoft.CodeAnalysis.AnalyzerConfig&text=AnalyzerConfig" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: text
    type: <xref href="Microsoft.CodeAnalysis.Text.SourceText?alt=Microsoft.CodeAnalysis.Text.SourceText&text=SourceText" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: pathToFile
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.Parse(Microsoft.CodeAnalysis.Text.SourceText,System.String)
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfig.Parse(Microsoft.CodeAnalysis.Text.SourceText,System.String)
  name: Parse(SourceText, String)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Parse(SourceText, String)
  nameWithType: AnalyzerConfig.Parse(SourceText, String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static Microsoft.CodeAnalysis.AnalyzerConfig Parse (Microsoft.CodeAnalysis.Text.SourceText text, string pathToFile);
      monikers:
      - roslyn-dotnet-3.1
      - roslyn-dotnet-3.2
      - roslyn-dotnet-3.2.1
      - roslyn-dotnet-3.3.1
      - roslyn-dotnet-3.4.0
      - roslyn-dotnet-3.5.0
      - roslyn-dotnet-3.6.0
      - roslyn-dotnet-3.7.0
      - roslyn-dotnet-3.8.0
    - value: public static Microsoft.CodeAnalysis.AnalyzerConfig Parse (Microsoft.CodeAnalysis.Text.SourceText text, string? pathToFile);
      monikers:
      - roslyn-dotnet-3.10.0
      - roslyn-dotnet-3.11.0
      - roslyn-dotnet-3.9.0
      - roslyn-dotnet-4.0.1
      - roslyn-dotnet-4.1.0
      - roslyn-dotnet-4.2.0
  - lang: fsharp
    values:
    - value: 'static member Parse : Microsoft.CodeAnalysis.Text.SourceText * string -> Microsoft.CodeAnalysis.AnalyzerConfig'
  - lang: vb
    values:
    - value: Public Shared Function Parse (text As SourceText, pathToFile As String) As AnalyzerConfig
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Parses an editor config file text located at the given path. No parsing

    errors are reported. If any line contains a parse error, it is dropped.
  metadata: {}
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfig?alt=Microsoft.CodeAnalysis.AnalyzerConfig&text=AnalyzerConfig" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: text
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  - namesWithMoniker:
    - value: pathToFile
    type: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.Parse(System.String,System.String)
  commentId: M:Microsoft.CodeAnalysis.AnalyzerConfig.Parse(System.String,System.String)
  name: Parse(String, String)
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Parse(String, String)
  nameWithType: AnalyzerConfig.Parse(String, String)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static Microsoft.CodeAnalysis.AnalyzerConfig Parse (string text, string pathToFile);
      monikers:
      - roslyn-dotnet-3.1
      - roslyn-dotnet-3.2
      - roslyn-dotnet-3.2.1
      - roslyn-dotnet-3.3.1
      - roslyn-dotnet-3.4.0
      - roslyn-dotnet-3.5.0
      - roslyn-dotnet-3.6.0
      - roslyn-dotnet-3.7.0
      - roslyn-dotnet-3.8.0
    - value: public static Microsoft.CodeAnalysis.AnalyzerConfig Parse (string text, string? pathToFile);
      monikers:
      - roslyn-dotnet-3.10.0
      - roslyn-dotnet-3.11.0
      - roslyn-dotnet-3.9.0
      - roslyn-dotnet-4.0.1
      - roslyn-dotnet-4.1.0
      - roslyn-dotnet-4.2.0
  - lang: fsharp
    values:
    - value: 'static member Parse : string * string -> Microsoft.CodeAnalysis.AnalyzerConfig'
  - lang: vb
    values:
    - value: Public Shared Function Parse (text As String, pathToFile As String) As AnalyzerConfig
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Parses an editor config file text located at the given path. No parsing

    errors are reported. If any line contains a parse error, it is dropped.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.Parse*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.Parse
namespace: Microsoft.CodeAnalysis
name: Parse
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Parse
nameWithType: AnalyzerConfig.Parse
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Parse
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Parse
  - Microsoft::CodeAnalysis::AnalyzerConfig::Parse
  - Parse
  - AnalyzerConfig.Parse
  - AnalyzerConfig::Parse
  helpviewer_keywords:
  - AnalyzerConfig.Parse method [.NET]
  - Parse method [.NET], class AnalyzerConfig
  - AnalyzerConfig.Parse(SourceText, String) method [.NET]
  - Parse(SourceText, String) method [.NET], class AnalyzerConfig
  - AnalyzerConfig.Parse(String, String) method [.NET]
  - Parse(String, String) method [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
