### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfigDocument?alt=Microsoft.CodeAnalysis.AnalyzerConfigDocument&text=AnalyzerConfigDocument" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: documentId
    type: <xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId)
  commentId: M:Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument(Microsoft.CodeAnalysis.DocumentId)
  name: GetAnalyzerConfigDocument(DocumentId)
  fullName: Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument(DocumentId)
  nameWithType: Project.GetAnalyzerConfigDocument(DocumentId)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.AnalyzerConfigDocument? GetAnalyzerConfigDocument (Microsoft.CodeAnalysis.DocumentId documentId);
      monikers:
      - roslyn-dotnet-3.10.0
      - roslyn-dotnet-3.11.0
      - roslyn-dotnet-3.3.1
      - roslyn-dotnet-3.4.0
      - roslyn-dotnet-3.5.0
      - roslyn-dotnet-3.6.0
      - roslyn-dotnet-3.7.0
      - roslyn-dotnet-3.8.0
      - roslyn-dotnet-3.9.0
      - roslyn-dotnet-4.0.1
      - roslyn-dotnet-4.1.0
      - roslyn-dotnet-4.2.0
    - value: public Microsoft.CodeAnalysis.AnalyzerConfigDocument GetAnalyzerConfigDocument (Microsoft.CodeAnalysis.DocumentId documentId);
      monikers:
      - roslyn-dotnet-3.2
      - roslyn-dotnet-3.2.1
  - lang: fsharp
    values:
    - value: 'member this.GetAnalyzerConfigDocument : Microsoft.CodeAnalysis.DocumentId -> Microsoft.CodeAnalysis.AnalyzerConfigDocument'
  - lang: vb
    values:
    - value: Public Function GetAnalyzerConfigDocument (documentId As DocumentId) As AnalyzerConfigDocument
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Get the analyzer config document in this project with the specified document Id.
  metadata: {}
uid: Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument*
commentId: Overload:Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument
namespace: Microsoft.CodeAnalysis
name: GetAnalyzerConfigDocument
fullName: Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument
nameWithType: Project.GetAnalyzerConfigDocument
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Project.GetAnalyzerConfigDocument
  - Microsoft::CodeAnalysis::Project::GetAnalyzerConfigDocument
  - GetAnalyzerConfigDocument
  - Project.GetAnalyzerConfigDocument
  - Project::GetAnalyzerConfigDocument
  helpviewer_keywords:
  - Project.GetAnalyzerConfigDocument method [.NET]
  - GetAnalyzerConfigDocument method [.NET], class Project
  - Project.GetAnalyzerConfigDocument(DocumentId) method [.NET]
  - GetAnalyzerConfigDocument(DocumentId) method [.NET], class Project
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
