### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.StringComparison?alt=System.StringComparison&text=StringComparison" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
  name: NameComparer
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
  nameWithType: AnalyzerConfig.Section.NameComparer
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static StringComparison NameComparer { get; }
  - lang: fsharp
    values:
    - value: 'member this.NameComparer : StringComparison'
  - lang: vb
    values:
    - value: Public Shared ReadOnly Property NameComparer As StringComparison
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: >-
    Used to compare <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfig.Section.Name"></xref>s of sections. Specified by editorconfig to

    be a case-sensitive comparison.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
namespace: Microsoft.CodeAnalysis
name: NameComparer
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
nameWithType: AnalyzerConfig.Section.NameComparer
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.get_NameComparer
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
  - Microsoft::CodeAnalysis::AnalyzerConfig::Section::NameComparer
  - NameComparer
  - Section.NameComparer
  - Section::NameComparer
  helpviewer_keywords:
  - AnalyzerConfig.Section.NameComparer property [.NET]
  - NameComparer property [.NET], class AnalyzerConfig.Section
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
