### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Immutable.ImmutableDictionary`2?alt=System.Collections.Immutable.ImmutableDictionary&text=ImmutableDictionary" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>,<xref href="Microsoft.CodeAnalysis.ReportDiagnostic?alt=Microsoft.CodeAnalysis.ReportDiagnostic&text=ReportDiagnostic" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions
  name: TreeOptions
  fullName: Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions
  nameWithType: AnalyzerConfigOptionsResult.TreeOptions
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Immutable.ImmutableDictionary<string,Microsoft.CodeAnalysis.ReportDiagnostic> TreeOptions { get; }
  - lang: fsharp
    values:
    - value: 'member this.TreeOptions : System.Collections.Immutable.ImmutableDictionary<string, Microsoft.CodeAnalysis.ReportDiagnostic>'
  - lang: vb
    values:
    - value: Public ReadOnly Property TreeOptions As ImmutableDictionary(Of String, ReportDiagnostic)
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Options that customize diagnostic severity as reported by the compiler.
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions
namespace: Microsoft.CodeAnalysis
name: TreeOptions
fullName: Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions
nameWithType: AnalyzerConfigOptionsResult.TreeOptions
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions
  - Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.get_TreeOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfigOptionsResult.TreeOptions
  - Microsoft::CodeAnalysis::AnalyzerConfigOptionsResult::TreeOptions
  - TreeOptions
  - AnalyzerConfigOptionsResult.TreeOptions
  - AnalyzerConfigOptionsResult::TreeOptions
  helpviewer_keywords:
  - AnalyzerConfigOptionsResult.TreeOptions property [.NET]
  - TreeOptions property [.NET], struct AnalyzerConfigOptionsResult
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
