### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions?alt=Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions&text=AnalyzerConfigOptions" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions
  commentId: P:Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions
  name: GlobalOptions
  fullName: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions
  nameWithType: AnalyzerConfigOptionsProvider.GlobalOptions
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public abstract Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions GlobalOptions { get; }
  - lang: fsharp
    values:
    - value: 'member this.GlobalOptions : Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions'
  - lang: vb
    values:
    - value: Public MustOverride ReadOnly Property GlobalOptions As AnalyzerConfigOptions
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Gets global options that do not apply to any specific file
  metadata: {}
uid: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions*
commentId: Overload:Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions
namespace: Microsoft.CodeAnalysis.Diagnostics
name: GlobalOptions
fullName: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions
nameWithType: AnalyzerConfigOptionsProvider.GlobalOptions
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.get_GlobalOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider.GlobalOptions
  - Microsoft::CodeAnalysis::Diagnostics::AnalyzerConfigOptionsProvider::GlobalOptions
  - GlobalOptions
  - AnalyzerConfigOptionsProvider.GlobalOptions
  - AnalyzerConfigOptionsProvider::GlobalOptions
  helpviewer_keywords:
  - AnalyzerConfigOptionsProvider.GlobalOptions property [.NET]
  - GlobalOptions property [.NET], class AnalyzerConfigOptionsProvider
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
