### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.GeneratorDriver?alt=Microsoft.CodeAnalysis.GeneratorDriver&text=GeneratorDriver" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: newOptions
    type: <xref href="Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider?alt=Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider&text=AnalyzerConfigOptionsProvider" data-throw-if-not-resolved="True"/>
  type: method
  uid: Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions(Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider)
  commentId: M:Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions(Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider)
  name: WithUpdatedAnalyzerConfigOptions(AnalyzerConfigOptionsProvider)
  fullName: Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions(AnalyzerConfigOptionsProvider)
  nameWithType: GeneratorDriver.WithUpdatedAnalyzerConfigOptions(AnalyzerConfigOptionsProvider)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.GeneratorDriver WithUpdatedAnalyzerConfigOptions (Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider newOptions);
  - lang: fsharp
    values:
    - value: 'member this.WithUpdatedAnalyzerConfigOptions : Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider -> Microsoft.CodeAnalysis.GeneratorDriver'
  - lang: vb
    values:
    - value: Public Function WithUpdatedAnalyzerConfigOptions (newOptions As AnalyzerConfigOptionsProvider) As GeneratorDriver
  monikers:
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  metadata: {}
uid: Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions*
commentId: Overload:Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions
namespace: Microsoft.CodeAnalysis
name: WithUpdatedAnalyzerConfigOptions
fullName: Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions
nameWithType: GeneratorDriver.WithUpdatedAnalyzerConfigOptions
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.GeneratorDriver.WithUpdatedAnalyzerConfigOptions
  - Microsoft::CodeAnalysis::GeneratorDriver::WithUpdatedAnalyzerConfigOptions
  - WithUpdatedAnalyzerConfigOptions
  - GeneratorDriver.WithUpdatedAnalyzerConfigOptions
  - GeneratorDriver::WithUpdatedAnalyzerConfigOptions
  helpviewer_keywords:
  - GeneratorDriver.WithUpdatedAnalyzerConfigOptions method [.NET]
  - WithUpdatedAnalyzerConfigOptions method [.NET], class GeneratorDriver
  - GeneratorDriver.WithUpdatedAnalyzerConfigOptions(AnalyzerConfigOptionsProvider) method [.NET]
  - WithUpdatedAnalyzerConfigOptions(AnalyzerConfigOptionsProvider) method [.NET], class GeneratorDriver
  monikers:
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
