### YamlMime:NetMember
type: field
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>
  type: field
  uid: Microsoft.CodeAnalysis.WellKnownGeneratorInputs.AnalyzerConfigOptions
  commentId: F:Microsoft.CodeAnalysis.WellKnownGeneratorInputs.AnalyzerConfigOptions
  name: AnalyzerConfigOptions
  fullName: Microsoft.CodeAnalysis.WellKnownGeneratorInputs.AnalyzerConfigOptions
  nameWithType: WellKnownGeneratorInputs.AnalyzerConfigOptions
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public const string AnalyzerConfigOptions;
  - lang: fsharp
    values:
    - value: 'val mutable AnalyzerConfigOptions : string'
  - lang: vb
    values:
    - value: 'Public Const AnalyzerConfigOptions As String '
  monikers:
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  metadata: {}
namespace: Microsoft.CodeAnalysis
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.WellKnownGeneratorInputs.AnalyzerConfigOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.WellKnownGeneratorInputs.AnalyzerConfigOptions
  - Microsoft::CodeAnalysis::WellKnownGeneratorInputs::AnalyzerConfigOptions
  - AnalyzerConfigOptions
  - WellKnownGeneratorInputs.AnalyzerConfigOptions
  - WellKnownGeneratorInputs::AnalyzerConfigOptions
  helpviewer_keywords:
  - WellKnownGeneratorInputs.AnalyzerConfigOptions field [.NET]
  - AnalyzerConfigOptions field [.NET], class WellKnownGeneratorInputs
  monikers:
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
