### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Immutable.ImmutableHashSet`1?alt=System.Collections.Immutable.ImmutableHashSet&text=ImmutableHashSet" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys
  name: ReservedKeys
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys
  nameWithType: AnalyzerConfig.ReservedKeys
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static System.Collections.Immutable.ImmutableHashSet<string> ReservedKeys { get; }
  - lang: fsharp
    values:
    - value: 'member this.ReservedKeys : System.Collections.Immutable.ImmutableHashSet<string>'
  - lang: vb
    values:
    - value: Public Shared ReadOnly Property ReservedKeys As ImmutableHashSet(Of String)
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  summary: >-
    A set of keys that are reserved for special interpretation for the editorconfig specification.

    All values corresponding to reserved keys in a (key,value) property pair are always lowercased

    during parsing.
  remarks: <p>This list was retrieved from https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties at 2018-04-21 19:37:05Z. New keys may be added to this list in newer versions, but old ones will not be removed.</p>
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys
namespace: Microsoft.CodeAnalysis
name: ReservedKeys
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys
nameWithType: AnalyzerConfig.ReservedKeys
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys
  - Microsoft.CodeAnalysis.AnalyzerConfig.get_ReservedKeys
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.ReservedKeys
  - Microsoft::CodeAnalysis::AnalyzerConfig::ReservedKeys
  - ReservedKeys
  - AnalyzerConfig.ReservedKeys
  - AnalyzerConfig::ReservedKeys
  helpviewer_keywords:
  - AnalyzerConfig.ReservedKeys property [.NET]
  - ReservedKeys property [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
