### YamlMime:NetMember
type: method
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Project?alt=Microsoft.CodeAnalysis.Project&text=Project" data-throw-if-not-resolved="True"/>
  parameters:
  - namesWithMoniker:
    - value: documentIds
    type: <xref href="System.Collections.Immutable.ImmutableArray`1?alt=System.Collections.Immutable.ImmutableArray&text=ImmutableArray" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.DocumentId?alt=Microsoft.CodeAnalysis.DocumentId&text=DocumentId" data-throw-if-not-resolved="True"/>&gt;
  type: method
  uid: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments(System.Collections.Immutable.ImmutableArray{Microsoft.CodeAnalysis.DocumentId})
  commentId: M:Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments(System.Collections.Immutable.ImmutableArray{Microsoft.CodeAnalysis.DocumentId})
  name: RemoveAnalyzerConfigDocuments(ImmutableArray<DocumentId>)
  fullName: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments(ImmutableArray<DocumentId>)
  nameWithType: Project.RemoveAnalyzerConfigDocuments(ImmutableArray<DocumentId>)
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.Project RemoveAnalyzerConfigDocuments (System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.DocumentId> documentIds);
  - lang: fsharp
    values:
    - value: 'member this.RemoveAnalyzerConfigDocuments : System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.DocumentId> -> Microsoft.CodeAnalysis.Project'
  - lang: vb
    values:
    - value: Public Function RemoveAnalyzerConfigDocuments (documentIds As ImmutableArray(Of DocumentId)) As Project
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Creates a new solution instance that no longer includes the specified <xref data-throw-if-not-resolved="true" uid="Microsoft.CodeAnalysis.AnalyzerConfigDocument"></xref>s.
  metadata: {}
uid: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments*
commentId: Overload:Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments
namespace: Microsoft.CodeAnalysis
name: RemoveAnalyzerConfigDocuments
fullName: Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments
nameWithType: Project.RemoveAnalyzerConfigDocuments
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Workspaces.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments
  api_location:
  - Microsoft.CodeAnalysis.Workspaces.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Project.RemoveAnalyzerConfigDocuments
  - Microsoft::CodeAnalysis::Project::RemoveAnalyzerConfigDocuments
  - RemoveAnalyzerConfigDocuments
  - Project.RemoveAnalyzerConfigDocuments
  - Project::RemoveAnalyzerConfigDocuments
  helpviewer_keywords:
  - Project.RemoveAnalyzerConfigDocuments method [.NET]
  - RemoveAnalyzerConfigDocuments method [.NET], class Project
  - Project.RemoveAnalyzerConfigDocuments(ImmutableArray<DocumentId>) method [.NET]
  - RemoveAnalyzerConfigDocuments(ImmutableArray<DocumentId>) method [.NET], class Project
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
