### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider?alt=Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider&text=AnalyzerConfigOptionsProvider" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions
  commentId: P:Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions
  name: AnalyzerConfigOptions
  fullName: Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions
  nameWithType: SourceGeneratorContext.AnalyzerConfigOptions
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider AnalyzerConfigOptions { get; }
  - lang: fsharp
    values:
    - value: 'member this.AnalyzerConfigOptions : Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider'
  - lang: vb
    values:
    - value: Public ReadOnly Property AnalyzerConfigOptions As AnalyzerConfigOptionsProvider
  monikers:
  - roslyn-dotnet-3.7.0
  summary: Allows access to options provided by an analyzer config
  metadata: {}
uid: Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions*
commentId: Overload:Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfigOptions
fullName: Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions
nameWithType: SourceGeneratorContext.AnalyzerConfigOptions
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.7.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.7.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions
  - Microsoft.CodeAnalysis.SourceGeneratorContext.get_AnalyzerConfigOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.SourceGeneratorContext.AnalyzerConfigOptions
  - Microsoft::CodeAnalysis::SourceGeneratorContext::AnalyzerConfigOptions
  - AnalyzerConfigOptions
  - SourceGeneratorContext.AnalyzerConfigOptions
  - SourceGeneratorContext::AnalyzerConfigOptions
  helpviewer_keywords:
  - SourceGeneratorContext.AnalyzerConfigOptions property [.NET]
  - AnalyzerConfigOptions property [.NET], struct SourceGeneratorContext
  monikers:
  - roslyn-dotnet-3.7.0
