### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.AnalyzerConfig.Section?alt=Microsoft.CodeAnalysis.AnalyzerConfig.Section&text=AnalyzerConfig.Section" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection
  name: GlobalSection
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection
  nameWithType: AnalyzerConfig.GlobalSection
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.AnalyzerConfig.Section GlobalSection { get; }
  - lang: fsharp
    values:
    - value: 'member this.GlobalSection : Microsoft.CodeAnalysis.AnalyzerConfig.Section'
  - lang: vb
    values:
    - value: Public ReadOnly Property GlobalSection As AnalyzerConfig.Section
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection
namespace: Microsoft.CodeAnalysis
name: GlobalSection
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection
nameWithType: AnalyzerConfig.GlobalSection
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection
  - Microsoft.CodeAnalysis.AnalyzerConfig.get_GlobalSection
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.GlobalSection
  - Microsoft::CodeAnalysis::AnalyzerConfig::GlobalSection
  - GlobalSection
  - AnalyzerConfig.GlobalSection
  - AnalyzerConfig::GlobalSection
  helpviewer_keywords:
  - AnalyzerConfig.GlobalSection property [.NET]
  - GlobalSection property [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
