### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.Collections.Immutable.ImmutableArray`1?alt=System.Collections.Immutable.ImmutableArray&text=ImmutableArray" data-throw-if-not-resolved="True"/>&lt;<xref href="Microsoft.CodeAnalysis.AnalyzerConfig.Section?alt=Microsoft.CodeAnalysis.AnalyzerConfig.Section&text=Section" data-throw-if-not-resolved="True"/>&gt;
  type: property
  uid: Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections
  commentId: P:Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections
  name: NamedSections
  fullName: Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections
  nameWithType: AnalyzerConfig.NamedSections
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.AnalyzerConfig.Section> NamedSections { get; }
  - lang: fsharp
    values:
    - value: 'member this.NamedSections : System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.AnalyzerConfig.Section>'
  - lang: vb
    values:
    - value: Public ReadOnly Property NamedSections As ImmutableArray(Of AnalyzerConfig.Section)
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  metadata: {}
uid: Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections*
commentId: Overload:Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections
namespace: Microsoft.CodeAnalysis
name: NamedSections
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections
nameWithType: AnalyzerConfig.NamedSections
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections
  - Microsoft.CodeAnalysis.AnalyzerConfig.get_NamedSections
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.NamedSections
  - Microsoft::CodeAnalysis::AnalyzerConfig::NamedSections
  - NamedSections
  - AnalyzerConfig.NamedSections
  - AnalyzerConfig::NamedSections
  helpviewer_keywords:
  - AnalyzerConfig.NamedSections property [.NET]
  - NamedSections property [.NET], class AnalyzerConfig
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
