### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider?alt=Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider&text=AnalyzerConfigOptionsProvider" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions
  commentId: P:Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions
  name: AnalyzerConfigOptions
  fullName: Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions
  nameWithType: GeneratorExecutionContext.AnalyzerConfigOptions
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider AnalyzerConfigOptions { get; }
  - lang: fsharp
    values:
    - value: 'member this.AnalyzerConfigOptions : Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptionsProvider'
  - lang: vb
    values:
    - value: Public ReadOnly Property AnalyzerConfigOptions As AnalyzerConfigOptionsProvider
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: Allows access to options provided by an analyzer config
  metadata: {}
uid: Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions*
commentId: Overload:Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfigOptions
fullName: Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions
nameWithType: GeneratorExecutionContext.AnalyzerConfigOptions
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions
  - Microsoft.CodeAnalysis.GeneratorExecutionContext.get_AnalyzerConfigOptions
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.GeneratorExecutionContext.AnalyzerConfigOptions
  - Microsoft::CodeAnalysis::GeneratorExecutionContext::AnalyzerConfigOptions
  - AnalyzerConfigOptions
  - GeneratorExecutionContext.AnalyzerConfigOptions
  - GeneratorExecutionContext::AnalyzerConfigOptions
  helpviewer_keywords:
  - GeneratorExecutionContext.AnalyzerConfigOptions property [.NET]
  - AnalyzerConfigOptions property [.NET], struct GeneratorExecutionContext
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
