### YamlMime:NetMember
type: property
members:
- returnsWithMoniker:
    type:
    - value: <xref href="System.StringComparer?alt=System.StringComparer&text=StringComparer" data-throw-if-not-resolved="True"/>
  type: property
  uid: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer
  commentId: P:Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer
  name: KeyComparer
  fullName: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer
  nameWithType: AnalyzerConfigOptions.KeyComparer
  syntaxWithMoniker:
  - lang: csharp
    values:
    - value: public static StringComparer KeyComparer { get; }
  - lang: fsharp
    values:
    - value: 'member this.KeyComparer : StringComparer'
  - lang: vb
    values:
    - value: Public Shared ReadOnly Property KeyComparer As StringComparer
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
  summary: >-
    Comparer that should be used for all analyzer config keys. This is a case-insensitive comparison based

    on Unicode case sensitivity rules for identifiers.
  metadata: {}
uid: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer*
commentId: Overload:Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer
namespace: Microsoft.CodeAnalysis.Diagnostics
name: KeyComparer
fullName: Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer
nameWithType: AnalyzerConfigOptions.KeyComparer
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.10.0
  monikers:
  - roslyn-dotnet-3.10.0
- value: Microsoft.CodeAnalysis.Common v3.11.0
  monikers:
  - roslyn-dotnet-3.11.0
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
- value: Microsoft.CodeAnalysis.Common v3.4.0
  monikers:
  - roslyn-dotnet-3.4.0
- value: Microsoft.CodeAnalysis.Common v3.5.0
  monikers:
  - roslyn-dotnet-3.5.0
- value: Microsoft.CodeAnalysis.Common v3.6.0
  monikers:
  - roslyn-dotnet-3.6.0
- value: Microsoft.CodeAnalysis.Common v3.7.0
  monikers:
  - roslyn-dotnet-3.7.0
- value: Microsoft.CodeAnalysis.Common v3.8.0
  monikers:
  - roslyn-dotnet-3.8.0
- value: Microsoft.CodeAnalysis.Common v3.9.0
  monikers:
  - roslyn-dotnet-3.9.0
- value: Microsoft.CodeAnalysis.Common v4.0.1
  monikers:
  - roslyn-dotnet-4.0.1
- value: Microsoft.CodeAnalysis.Common v4.1.0
  monikers:
  - roslyn-dotnet-4.1.0
- value: Microsoft.CodeAnalysis.Common v4.2.0
  monikers:
  - roslyn-dotnet-4.2.0
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet
- roslyn-dotnet-3.1
- roslyn-dotnet-3.10.0
- roslyn-dotnet-3.11.0
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
- roslyn-dotnet-3.4.0
- roslyn-dotnet-3.5.0
- roslyn-dotnet-3.6.0
- roslyn-dotnet-3.7.0
- roslyn-dotnet-3.8.0
- roslyn-dotnet-3.9.0
- roslyn-dotnet-4.0.1
- roslyn-dotnet-4.1.0
- roslyn-dotnet-4.2.0
metadata:
  api_name:
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.get_KeyComparer
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.Diagnostics.AnalyzerConfigOptions.KeyComparer
  - Microsoft::CodeAnalysis::Diagnostics::AnalyzerConfigOptions::KeyComparer
  - KeyComparer
  - AnalyzerConfigOptions.KeyComparer
  - AnalyzerConfigOptions::KeyComparer
  helpviewer_keywords:
  - AnalyzerConfigOptions.KeyComparer property [.NET]
  - KeyComparer property [.NET], class AnalyzerConfigOptions
  monikers:
  - roslyn-dotnet
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.10.0
  - roslyn-dotnet-3.11.0
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
  - roslyn-dotnet-3.4.0
  - roslyn-dotnet-3.5.0
  - roslyn-dotnet-3.6.0
  - roslyn-dotnet-3.7.0
  - roslyn-dotnet-3.8.0
  - roslyn-dotnet-3.9.0
  - roslyn-dotnet-4.0.1
  - roslyn-dotnet-4.1.0
  - roslyn-dotnet-4.2.0
