### YamlMime:NetType
type: class
inheritancesWithMoniker:
- values:
  - <xref href="System.Object?alt=System.Object&text=Object" data-throw-if-not-resolved="True"/>
constructors:
- uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.#ctor(System.String,System.Collections.Immutable.ImmutableDictionary{System.String,System.String})
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
properties:
- uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.Name
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
- uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.NameComparer
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
- uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.Properties
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
- uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section.PropertiesKeyComparer
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
uid: Microsoft.CodeAnalysis.AnalyzerConfig.Section
commentId: T:Microsoft.CodeAnalysis.AnalyzerConfig.Section
namespace: Microsoft.CodeAnalysis
name: AnalyzerConfig.Section
fullName: Microsoft.CodeAnalysis.AnalyzerConfig.Section
nameWithType: Microsoft.CodeAnalysis.AnalyzerConfig.Section
assembliesWithMoniker:
- value: Microsoft.CodeAnalysis.dll
packagesWithMoniker:
- value: Microsoft.CodeAnalysis.Common v3.1.0
  monikers:
  - roslyn-dotnet-3.1
- value: Microsoft.CodeAnalysis.Common v3.2.0
  monikers:
  - roslyn-dotnet-3.2
- value: Microsoft.CodeAnalysis.Common v3.2.1
  monikers:
  - roslyn-dotnet-3.2.1
- value: Microsoft.CodeAnalysis.Common v3.3.1
  monikers:
  - roslyn-dotnet-3.3.1
syntaxWithMoniker:
- lang: csharp
  values:
  - value: public sealed class AnalyzerConfig.Section
- lang: fsharp
  values:
  - value: type AnalyzerConfig.Section = class
- lang: vb
  values:
  - value: Public NotInheritable Class AnalyzerConfig.Section
devLangs:
- csharp
- vb
- fsharp
monikers:
- roslyn-dotnet-3.1
- roslyn-dotnet-3.2
- roslyn-dotnet-3.2.1
- roslyn-dotnet-3.3.1
summary: >-
  Represents a named section of the editorconfig file, which consists of a name followed by a set

  of key-value pairs.
metadata:
  api_name:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section
  api_location:
  - Microsoft.CodeAnalysis.dll
  topic_type:
  - apiref
  api_type:
  - Assembly
  f1_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section
  - Microsoft::CodeAnalysis::AnalyzerConfig::Section
  - Section
  helpviewer_keywords:
  - Microsoft.CodeAnalysis.AnalyzerConfig.Section class [.NET]
  monikers:
  - roslyn-dotnet-3.1
  - roslyn-dotnet-3.2
  - roslyn-dotnet-3.2.1
  - roslyn-dotnet-3.3.1
